language: node_js
node_js:
  - '10.15.0'

sudo: required

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
      - libsecret-1-dev

install:
  - docker --version
  - docker-compose --version

script:
  - npm ci
  - docker-compose up -d
  - npm run deploy
  - docker-compose logs graph-node
  - npm run jest -- test/integration/SubscriptionLoop.spec.ts
  # single test runs
  - npm run jest -- test/integration/Subscription.spec.ts
  # running the test in quick succession fails
  - for run in {1..10}; do sleep 3 && npm run jest -- test/integration/Subscription.spec.ts ; done

after_script:
  - npm run docker:stop
