language: nodejs
node_js:
  - "10.13.0"

sudo: required

services:
  - docker

install:
  - apt-get install jq

script:
  - npm install
  - npm run build
  - docker build . -t daostack/ganache:$(cat package.json | jq -r '.version') # tag with package version

deploy:
  provider: script
  script: "npm publish && docker push daostack/ganache"
  on:
    branch: master
