language: node_js
node_js:
  - '10.15.0'

sudo: required

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
      - libsecret-1-dev

install:
  - docker --version
  - docker-compose --version

script:

  # - docker-compose up -d graph-node
  - docker-compose up  -d
  - docker images --digests | grep graph-node

  - docker-compose logs graph-node

  - echo 'npm ci:' && echo -en 'travis_fold:start:script.3\\r'
  - npm ci
  - echo -en 'travis_fold:end:script.3\\r'
  - npm run deploy

  # run deploy twice to see if it reproduces the error
  - npm run deploy

  - docker-compose logs graph-node
  # single test runs
  - npm run jest -- test/integration/Subscription.spec.ts
  # running the test in quick succession fails
  - npm run jest -- test/integration/SubscriptionLoop.spec.ts
  - for run in {1..10}; do npm run jest -- test/integration/Subscription.spec.ts ; done
  # running test again files
  - npm run jest -- test/integration/Subscription.spec.ts

after_script:
  - npm run docker:stop
