language: node_js
node_js:
  - '10.15.0'

sudo: required

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
      - libsecret-1-dev

install:
  - docker --version
  - docker-compose --version

script:
  - docker-compose up -d graph-node
  - docker-compose logs graph-node

  - echo 'npm ci:' && echo -en 'travis_fold:start:script.1\\r'
  - npm ci
  - echo -en 'travis_fold:end:script.1\\r'

  # deploy contracts etc
  - npm run deploy

  - echo 'Debug info:' && echo -en 'travis_fold:start:script.2\\r'
  - docker images --digests | grep graph-node
  - docker-compose logs graph-node
  - echo -en 'travis_fold:end:script.2\\r'

  - npm run test

after_script:
  - npm run docker:stop
