language: node_js
cache: npm
node_js:
  - "10.14.1"

sudo: required

services:
  - docker
notifications:
  email: false
node_js:
  - node

before_install:
  - sudo apt-get install libsecret-1-dev
script:
  # start the subgraph docker containers
  - npm ci
  - docker-compose up -d graph-node
  - ./scripts/wait-for-it.sh 127.0.0.1:8545
  - ./scripts/wait-for-it.sh localhost:8545
  - ./scripts/wait-for-it.sh 127.0.0.1:8000
  - ./scripts/wait-for-it.sh 127.0.0.1:8020
  - sleep 15
  - npm run setup-env
  - npm run lint
  - npm run test
  - npm run build
  - docker-compose down -v
after_success:
  - npm run report-coverage
  - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
  - test $TRAVIS_BRANCH = "master" && npm run semantic-release
