language: node_js
cache: npm
#   npm: true
#   directories:
#     - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod
  - npm run build
after_success:
  - npm run report-coverage
  - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
  - test $TRAVIS_BRANCH = "master" && npm run semantic-release
