language: node_js
cache: npm
node_js:
  - "10.13.0"

sudo: required

services:
  - docker
notifications:
  email: false
node_js:
  - node
script:
  - git clone https://github.com/daostack/subgraph.git /subgraph
  - cd /subgraph && npm install
  - cd /subgraph && npm run configure:development
  - cd /subgraph && npm run codegen
  # - cd /subgraph && sudo docker-compose build
  - cd /subgraph && sudo docker-compose up --daemon
  - sleep 5
  - npm run test:prod
  - npm run build
after_success:
  - npm run report-coverage
  - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
  - test $TRAVIS_BRANCH = "master" && npm run semantic-release
